export const SKILL_LEVEL_BEGINNER = 'BEGINNER';
export const SKILL_LEVEL_INTERMEDIATE = 'INTERMEDIATE';
export const SKILL_LEVEL_ADVANCED = 'ADVANCED';

export const SKILL_LEVELS = [
  SKILL_LEVEL_BEGINNER,
  SKILL_LEVEL_INTERMEDIATE,
  SKILL_LEVEL_ADVANCED,
];

export default SKILL_LEVELS;
